# Generated by Django 2.1 on 2018-08-23 06:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APDMP_Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=254)),
                ('state_ut', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='APDMP_Mandals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_distri', models.CharField(max_length=254)),
                ('district', models.CharField(max_length=254)),
                ('state_ut', models.CharField(max_length=254)),
                ('assignment', models.CharField(max_length=25)),
                ('lfa', models.CharField(max_length=25)),
                ('fa', models.CharField(max_length=25)),
                ('sno', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='APDMP_Villages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_id', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('sub_distri', models.CharField(max_length=254)),
                ('district', models.CharField(max_length=254)),
                ('state_ut', models.CharField(max_length=254)),
                ('c_code01', models.CharField(max_length=254)),
                ('lfa', models.CharField(max_length=80)),
                ('fa', models.CharField(max_length=80)),
                ('gp', models.CharField(max_length=80)),
                ('hi_depth', models.IntegerField()),
                ('pumpdepth', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='APDMP_Districs',
        ),
    ]
