# Generated by Django 2.1 on 2018-08-23 14:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_auto_20180823_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='AP_Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=75)),
                ('district', models.CharField(max_length=75)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
